### ISSUE TITLE
Hook appIntegrity - Protecting an Android app against tampering what percentage of effectiveness does the basic plan provide?

### ISSUE THREAD

**Issue by jazael** [talsec/Free-RASP-Community#25]
**Describe the bug**
The security team performed a test by manipulating the Android application, i.e. the installer in .apk format.
The antiTamper protection was breached using reverse engineering + deobfuscation techniques. Attached images with the evidence show that it was possible to modify the Java code removing the antiTamper detection, repack the apk with another signature, change the name of the app and some icons as a Demo.

**To Reproduce**
We reverse engineered, changed logos, icons, removed Java code by removing the antiTamper detection, then proceeded to repack the apk with another signature.

**Expected behavior**
As a result, I was hoping that the community version would help to mitigate this vulnerability, I understand that it is a basic protection, but I would like to understand to what extent it can help, so that I can think about purchasing the licensed plan.

**Screenshots**
![image](https://github.com/talsec/Free-RASP-Community/assets/11983683/e4c19408-fa66-419f-9fba-97fcb0d08780)

**Please complete the following information:**
 - Device: Samsung Galaxy A50
 - OS version: Android 12
 - Version of freeRASP: 3.1.0

**Comment by SirionRazzer** [comment]
Hi @jazael,
I understand your concerns. I appreciate your commitment to verify the SDK features. That's the right way to do it!

To answer your questions. You probably instrument the bytecode related to integrity checking. However, in the Business RASP+, **there are additional checks** not only in the bytecode layer. These are much harder to bypass. Ultimately, you may be interested in the AppiCrypt solution, which can solve most of the issues you are probably tackling. Check the comparison table to understand the differences between the free and commercial versions.

**Differences between freeRASP and Business RASP+**: https://github.com/orgs/talsec/discussions/5
**Comparison table**: https://www.talsec.app/freerasp-in-app-protection-security-talsec
**AppiCrypt**: https://www.talsec.app/appicrypt

If you haven't had the opportunity to engage in a face-to-face conversation with us yet, we will happily answer your questions and suggest possible solutions; just pick a time slot in Calendly: https://calendly.com/sergiy-yakymchuk-1/60min?month=2022-07

Thank you, and have a great day!

Best Regards,
Tomas Soukal

**Comment by talsec-app** [comment]
Which deobfuscation tools do you use? @jazael
