### ISSUE TITLE
Which OWASP measures are fulfilled?

### ISSUE THREAD

**Issue by cpholguera** [talsec/Free-RASP-Community#3]
The README says "Fulfills OWASP Code Tampering and Reverse Engineering measures". Are you referring to the OWASP MASVS?

https://mas.owasp.org/MASVS/Controls/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements/

Thank you!

**Comment by syakymchuk** [comment]
Hello @cpholguera, 

I confirm that freeRASP has a basic coverage of all MASVS Reverse Engineering and Tampering requirements 8.1-8.9. But, you should keep in mind that it has many limitations compared to the commercial RASP+ and AppiCrypt technology.   freeRASP is a good start and basis, but for commercial and valuable app protection, Business products are preferred. Feel free to request a meeting here https://www.talsec.app/contact, and I will be happy to explain the details.

**Comment by cpholguera** [comment]
Ha @syakymchuk, thanks for the answer. I'm the leader of the MASVS standard so it is very interesting to see this. Would you mind including a link to the MASVS here and in your website so that people can find their way there? 

https://mas.owasp.org/MASVS/

Thank you very much!


If you'd like to connect with us please take a look here: https://mas.owasp.org/contact/

**Comment by syakymchuk** [comment]
Hi @cpholguera. We refer to Mobile Owasp on the web and our commercial product documentation. I will ask the team to make this more visible on GitHub. Thank you for your feedback. I would be glad for your elaboration of our technology. I belive we have some valuable insights to contribute to the overall mobile app security and Owasp team working on this subject. 
![image](https://user-images.githubusercontent.com/85942457/193763747-bf40f719-8ab1-4529-af7f-e961d49cf8b0.png)

I will contact you via the link provided.

Good luck and have a great day!

**Comment by cpholguera** [comment]
Sounds great @syakymchuk, thank you!
