### ISSUE TITLE
iOS Weekly Report with 3.7 million devices

### ISSUE THREAD

**Issue by ikosta** [talsec/Free-RASP-Community#36]
**Describe the bug**
We got the weekly report with over 3.7 million devices. This can't be our app. Maybe an other app or even all devices you have.

**To Reproduce**
regenerate the report for iOS.

**Expected behavior**
Only get the weekly report data for our app.

**Screenshots**
Can give you the report on request. Won't put the data here publicly.

**Please complete the following information:**
 - Device: PDF weekly report
 - OS version: PDF weekly report
 - Version of freeRASP: PDF weekly report

**Additional context**
None.

**Comment by msikyna** [comment]
Hello @ikosta ,

that's quite strange. Could you please send us the reports at support@talsec.app along with your watcherMail and packageName/bundleId? Thank you!

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello,

the issue has been fixed. Thank you for reporting it!

Kind regards,
Talsec team
