### ISSUE TITLE
Getting 'Unknown Kotlin JVM target: 21' if build the project with JDK 21

### ISSUE THREAD

**Issue by rajurevoori** [talsec/Free-RASP-Community#56]
**Describe the bug**
In new Android Studio(Ladybug | 2024.2.1 Patch 1 which released on Build #AI-242.23339.11.2421.12483815, built on October 11, 2024) default android gradle JDK version set to 21. When we add this plugin and try to run the app getting below error.

org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':capacitor-freerasp:compileDebugKotlin'.
Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 21

**To Reproduce**
- Add this plugin to ionic capacitor project.
- Update gradle JDK to 21
- Build the app.

**Expected behavior**
We should not get any kotlin compatable error with JDK 21

**Screenshots**

**Please complete the following information:**
Build issue.
 - Version of freeRASP:1.4.0, 1.5.2

**Additional context**
At least add below kotlin options in the plugin gradle.
kotlinOptions { jvmTarget = "17" }

**Comment by msikyna** [comment]
Duplicate: https://github.com/talsec/Free-RASP-Capacitor/issues/21
